name: .NET lint

# Note: this action requires .NET 6+ SDK

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  SHELL:
    required: false
    type: string
    default: "bash"

runs:
  using: composite
  steps:
    - name: .NET lint
      shell: ${{ inputs.SHELL }}
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        dotnet format style --verify-no-changes
        dotnet format analyzers --verify-no-changes
