name: .NET install, build and publish

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  DOTNET_VERSION:
    required: true
    type: string
  BUILD_CONFIG:
    required: true
    type: string
  PROJECT:
    requires: true
    type: string
  OUTPUT_DIRECTORY:
    required: true
    type: string
  ALPINE_OS:
    required: false
    type: string
    default: false
  SHELL:
    required: false
    type: string
    default: 'bash'

runs:
  using: composite
  steps:
    - name: Install .NET
      uses: zupit-it/pipeline-templates/.github/actions/dotnet/install@v1.2.0
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        DOTNET_VERSION: ${{ inputs.DOTNET_VERSION }}
        ALPINE_OS: ${{ inputs.ALPINE_OS }}
        SHELL: ${{ inputs.SHELL }}

    - name: Build
      uses: zupit-it/pipeline-templates/.github/actions/dotnet/build@v1.2.0
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        BUILD_CONFIG: ${{ inputs.BUILD_CONFIG }}
        SHELL: ${{ inputs.SHELL }}

    - name: Publish
      uses: zupit-it/pipeline-templates/.github/actions/dotnet/publish@v1.2.0
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        PROJECT: ${{ inputs.PROJECT }}
        OUTPUT_DIRECTORY: ${{ inputs.OUTPUT_DIRECTORY }}
        BUILD_CONFIG: ${{ inputs.BUILD_CONFIG }}
        SHELL: ${{ inputs.SHELL }}
