name: .NET format

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  SHELL:
    required: false
    type: string
    default: "bash"
  CSHARPIER_VERSION:
    required: false
    type: string
    default: ""

runs:
  using: composite
  steps:
    - name: Setup CSharpier
      uses: actions/cache@v3
      id: csharpier-cache
      with:
        path: /tmp/dotnet-tools
        key: ${{ runner.os }}-csharpier-${{ inputs.CSHARPIER_VERSION || 'latest' }}

    - name: Install CSharpier
      if: steps.csharpier-cache.outputs.cache-hit != 'true'
      shell: ${{ inputs.SHELL }}
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        dotnet tool update --tool-path /tmp/dotnet-tools csharpier ${{ inputs.CSHARPIER_VERSION != '' && format('--version {0}', inputs.CSHARPIER_VERSION) || '' }}

    - name: Check code formatting
      shell: ${{ inputs.SHELL }}
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: /tmp/dotnet-tools/dotnet-csharpier . --check
