name: Conventional Commits Release Step

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_NATIVE_GROUP:
        required: false
        type: string
        default: 'Native'

jobs:
  release:
    name: release
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_NATIVE_GROUP }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
