name: Conventional Commits Release Step

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string

jobs:
  release:
    name: release
    runs-on: ${{ fromJson(inputs.LABELS) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm ci --ignore-scripts
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
