name: Conventional Commits Lint Step

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      CONFIG_FILE:
        required: true
        type: string
        default: .commitlintrc

jobs:
  lint-commits:
    name: Lint Commits
    runs-on: ${{ fromJson(inputs.LABELS) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ${{ inputs.CONFIG_FILE }}

  lint-pr:
    name: Lint PR
    runs-on: ${{ fromJson(inputs.LABELS) }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
