name: Conventional Commits Lint Step

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      CONFIG_FILE:
        required: true
        type: string
        default: .commitlintrc

jobs:
  lint-pr:
    name: Lint PR
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container: node:20-alpine
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
