name: Django Check Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
      DJANGO_APPS:
        required: false
        type: string
        default: ""

env: "${{secrets}}"

jobs:
  django-check:
    runs-on: ${{ fromJson(inputs.LABELS) }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django-runner
          POSTGRES_PASSWORD: django-runner
          POSTGRES_DB: django

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: ${{ inputs.WORKING_DIRECTORY }}/requirements.txt
      - name: Copy env file
        run: cp .env.gitlab .env
      - name: Django check and validate templates
        run: |
         python manage.py check
         python manage.py validate_templates
      - name: Django validate migrations
        run: |
         python manage.py makemigrations ${DJANGO_MIGRATIONS_CHECK_APPS} --check --dry-run
         python manage.py migrate --fake --no-input
