name: Django Linter Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      DJANGO_IMAGE:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string

jobs:
  django-linter:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container: ${{ inputs.DJANGO_IMAGE }}

    steps:
      - name: Install dependencies
        run: |
          cd ${{ inputs.DJANGO_PATH }}
          if [ -f lint-requirements.txt ]; then pip install -r lint-requirements.txt; fi
      - name: Lint with flake8
        run: |
         cd ${{ inputs.DJANGO_PATH }}
         python -m flake8 .
      - name: Lint with black
        run: |
         cd ${{ inputs.DJANGO_PATH }}
         python -m black --check .
