name: Run Django tests

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      PYTHON_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: true
        type: string
      RUN:
        required: false
        type: boolean
        default: true

env: "${{secrets}}"

jobs:
  django-tests:
    if: ${{ inputs.RUN }}
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container: ${{ inputs.PYTHON_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django-runner
          POSTGRES_PASSWORD: django-runner
          POSTGRES_DB: django
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Copy env file
        run: cp .env.github .env
      - name: Migrate django DB
        run: python manage.py migrate
      - name: Run django tests
        run: |
         coverage erase
         coverage run --source='.' manage.py test --noinput
         coverage xml -i -o coverage-reports/coverage-django.xml
         coverage report --fail-under 50 

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
          path: ${{ inputs.WORKING_DIRECTORY }}/coverage-reports/coverage-django.xml
          retention-days: 1

      - run: echo "Done!"