name: Django Build and Push Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string
      BUILT_DJANGO_IMAGE:
        required: true
        type: string
      BUILT_DJANGO_IMAGE_VERSION:
        required: true
        type: string
      DJANGO_DOCKER_PATH:
        required: true
        type: string

env:
  REGISTRY_URL: ghcr.io

jobs:
  django-build-image:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ env.REGISTRY_URL }}/${{ github.repository }}/${{ inputs.BUILT_DJANGO_IMAGE }}
          tags: ${{ inputs.BUILT_DJANGO_IMAGE_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.DJANGO_PATH }}
          file: ${{ inputs.DJANGO_PATH }}/${{ inputs.DJANGO_DOCKER_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

