name: Django Check Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      DJANGO_IMAGE:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string
      DJANGO_MIGRATIONS_CHECK_APPS:
        required: false
        type: string
        default: ""

env: "${{secrets}}"

jobs:
  build:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container:
      image: ${{ inputs.DJANGO_IMAGE }}

    services:
      postgres:
        image: postgres:12.5-alpine
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd ${{ inputs.DJANGO_PATH }}
          cp .env.gitlab .env
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Copy env file
        run: |
          cd ${{ inputs.DJANGO_PATH }}
          cp .env.gitlab .env
      - name: Django check and validate templates
        run: |
         cd ${{ inputs.DJANGO_PATH }}
         python manage.py check
         python manage.py validate_templates
      - name: Django validate migrations
        run: |
         cd ${{ inputs.DJANGO_PATH }}
         python manage.py makemigrations ${DJANGO_MIGRATIONS_CHECK_APPS} --check --dry-run
         python manage.py migrate --fake --no-input
