name: Django Full Workflow

on:
  workflow_call:
    inputs:
      # Projects inputs
      DJANGO_IMAGE:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string
      DJANGO_MIGRATIONS_CHECK_APPS:
        required: false
        type: string
        default: ""
      # Workflow inputs
      DJANGO_CI_LABELS:
        required: true
        type: string

jobs:
  django-linter:
    uses:
      .github/workflows/django-step-linter.yml
    with:
      DJANGO_IMAGE: ${{inputs.DJANGO_IMAGE}}
      DJANGO_PATH: ${{inputs.DJANGO_PATH}}
      LABELS: ${{inputs.DJANGO_CI_LABELS}}

  django-check:
    uses:
      .github/workflows/django-step-check.yml
    with:
      DJANGO_IMAGE: ${{inputs.DJANGO_IMAGE}}
      DJANGO_PATH: ${{inputs.DJANGO_PATH}}
      LABELS: ${{inputs.DJANGO_CI_LABELS}}
