name: Sonar analyze with artifacts

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  django-sonar-analyze:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container:
      image: ${{ inputs.SONAR_IMAGE }}
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: ${{ inputs.WORKING_DIRECTORY }}/coverage-reports/coverage-django.xml
      - run: ls -R
      - run: ls -R backend
      - run: ls -R backend/coverage-reports
      - name: Check artifact
        run: cat ${{ inputs.WORKING_DIRECTORY }}/coverage-reports/coverage-django.xml
