name: Django Full Workflow

on:
  workflow_call:
    inputs:
      # Projects inputs
      DJANGO_IMAGE:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string
      DJANGO_MIGRATIONS_CHECK_APPS:
        required: false
        type: string
        default: ""
      BUILT_DJANGO_IMAGE: #da spostare negli altri workflow (testing, staging, ..)
        required: false
        type: string
        default: django
      DJANGO_DOCKER_PATH: #da spostare negli altri workflow (testing, staging, ..)
        required: true
        type: string
      # Workflow inputs
      DJANGO_CI_LABELS:
        required: true
        type: string

jobs:
  django-tests:
    runs-on: ${{ fromJson(inputs.DJANGO_CI_LABELS) }}

    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Coverage action
        uses: actions/python-django-coverage-gitHub-action@0.9
        with:
          django-app: ${{inputs.DJANGO_PATH}}
          minimum-coverage: '86'

  django-vulnerability:
    runs-on: ${{ fromJson(inputs.DJANGO_CI_LABELS) }}

    steps:
      - name: Check out master
        uses: actions/checkout@v2
      - name: Scan Django settings for security issues
        id: check
        uses: victoriadrake/django-security-check@master
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: security-check-output
          path: output.txt


