name: Django Tests Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
      DJANGO_APPS:
        required: false
        type: string
        default: ""

env: "${{secrets}}"

jobs:
  django-tests:
    runs-on: ${{ fromJson(inputs.LABELS) }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django-runner
          POSTGRES_PASSWORD: django-runner
          POSTGRES_DB: django
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: ${{ inputs.WORKING_DIRECTORY }}/lint-requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install coverage
        run: pip install coverage
      - name: Copy env file
        run: cp .env.gitlab .env
      - name: Migrate django DB
        run: python manage.py migrate
      - name: Run django tests
        run: |
         coverage erase
         coverage run --source='.' manage.py test --noinput
         coverage xml -i -o coverage-reports/coverage-django.xml
         coverage report --fail-under 50 

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ${{ inputs.WORKING_DIRECTORY }}/coverage-reports/coverage-django.xml
          retention-days: 1
