name: Deploy docker compose

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DEPLOY_URL:
        required: true
        type: string
      REGISTRY_URL:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      DOCKER_COMPOSE_PATH:
        required: true
        type: string
      DOCKER_COMPOSE_EXTRA_ARGS:
        required: false
        type: string
        default: ''
      IMAGES:
        required: true
        type: string

env: "${{secrets}}"

jobs:
  deploy:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    env: ${{ fromJson(inputs.IMAGES) }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.DEPLOY_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} pull
      - run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} down
      - run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} up -d --build
