name: Deploy docker compose

on:
  workflow_call:
    inputs:
      DEPLOY_ON:
        required: true
        type: string
      RUNNERS_NATIVE_GROUP:
        required: false
        type: string
        default: 'Native'
      ENVIRONMENT:
        required: true
        type: string
      DEPLOY_URL:
        required: true
        type: string
      REGISTRY_URL:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      DOCKER_COMPOSE_PATH:
        required: true
        type: string
      DOCKER_COMPOSE_EXTRA_ARGS:
        required: false
        type: string
        default: ''
      IMAGES:
        required: true
        type: string
      DIND_IMAGE:
        required: false
        type: string
        default: 'docker:26.0.0-dind'

env: "${{secrets}}"

jobs:
  deploy:
    runs-on:
      labels:
        - deploy
        - ${{ inputs.DEPLOY_ON }}
      group: ${{ inputs.RUNNERS_NATIVE_GROUP }}
    env: ${{ fromJson(inputs.IMAGES) }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.DEPLOY_URL }}
    container:
      image: ${{ inputs.DIND_IMAGE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} pull
      - run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} up --build --remove-orphans --force-recreate -d
