name: Docker build and push image

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      REGISTRY_URL:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        required: true
        type: string
      DOCKER_IMAGE_TAG:
        required: true
        type: string
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      REGISTRY_USER:
        required: false
        type: string
        default: ${{ github.actor }}
      REGISTRY_PASSWORD:
        required: false
        type: string
        default: ${{ github.token }}
    outputs:
      DOCKER_IMAGE_NAME:
        description: "The docker image name that has been built"
        value: ${{ jobs.docker-build-push-image.outputs.DOCKER_IMAGE_NAME }}

env: "${{secrets}}"

jobs:
  docker-build-push-image:
    runs-on: ${{ fromJson(inputs.LABELS) }}

    outputs:
      DOCKER_IMAGE_NAME: ${{ steps.docker.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Build & Push
        id: docker
        uses: ./.github/actions/docker-build-and-push
        with:
          REGISTRY_URL: ${{ inputs.REGISTRY_URL }}
          REGISTRY_USER: ${{ inputs.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ inputs.REGISTRY_PASSWORD }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          DOCKERFILE_PATH: ${{ inputs.DOCKERFILE_PATH }}
          DOCKER_IMAGE_NAME: ${{ inputs.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
          BUILD_ARGS: ${{ inputs.BUILD_ARGS }}
        env: "${{secrets}}"


