name: .NET common

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      DOTNET_IMAGE:
        required: true
        type: string
      CONTAINER_CI_LABELS:
        required: true
        type: string

jobs:
  dotnet-common:
    name: Run .NET build, check formatting and test
    runs-on: ${{ fromJson(inputs.CONTAINER_CI_LABELS) }}
    container:
      image: ${{ inputs.DOTNET_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/build@v1.8.0
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_CONFIG: "Debug"

      - name: Check code formatting
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/format@v1.8.0
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}

      - name: Run tests
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/test@v1.8.0
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          GENERATE_CODE_COVERAGE: false
