name: .NET common

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      DOTNET_IMAGE:
        required: true
        type: string
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: 'Container'
      DOTNET_IMAGE_ENV_VARIABLES:
        required: false
        type: string
        default: '{}'
      CSHARPIER_VERSION:
        required: false
        type: string
        default: ''
      RUN_LINT:
        required: false
        type: boolean
        default: true

jobs:
  dotnet-common:
    name: Run .NET build, check formatting and test
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.DOTNET_IMAGE }}
      env: ${{ fromJson(inputs.DOTNET_IMAGE_ENV_VARIABLES) }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check code formatting
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/format@v1.21.1
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          CSHARPIER_VERSION: ${{ inputs.CSHARPIER_VERSION }}

      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/build@v1.21.1
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_CONFIG: "Debug"

      - name: Lint
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/lint@v1.21.1
        if: ${{ inputs.RUN_LINT == 'true' }}
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}

      - name: Run tests
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/test@v1.21.1
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          GENERATE_CODE_COVERAGE: false
