name: .NET common

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      DOTNET_VERSION:
        required: true
        type: string
      LABELS:
        required: true
        type: string

jobs:
  dotnet-common:
    name: Run .NET build, check formatting and test
    runs-on: ${{ fromJson(inputs.LABELS) }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/install@MIGI-40/dotnet-workflows
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          DOTNET_VERSION: ${{ inputs.DOTNET_VERSION }}
          ALPINE_OS: false
          SHELL: ${{ inputs.SHELL }}

      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/build@MIGI-40/dotnet-workflows
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_CONFIG: "Debug"

      - name: Check code formatting
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/format@MIGI-40/dotnet-workflows
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}

      - name: Run tests
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/test@MIGI-40/dotnet-workflows
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
