name: Jira Issue Transition

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      STATUS:
        required: true
        type: string
      BRANCH_OR_COMMIT_TITLE:
        required: true
        type: string

jobs:
  move-jira-issue:
    runs-on: ${{ fromJson(inputs.LABELS) }}

    steps:
      - name: Setup
        uses: atlassian/gajira-cli@v3
        with:
          version: 1.0.27

      - name: Login to Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find issue key
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ inputs.BRANCH_OR_COMMIT_TITLE }}
        continue-on-error: true

      - name: Check issue status
        id: check-status
        shell: 'bash'
        if: steps.find.outcome == 'success'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          output=$(jira view ${{ steps.find.outputs.issue }} --field status -e ${{ secrets.JIRA_BASE_URL }} --login ${{ secrets.JIRA_USER_EMAIL }} | sed -n 's/status: \(.*\)/\L\1/p')
          echo "status=$output" >> "$GITHUB_OUTPUT"

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: steps.find.outcome == 'success' && steps.check-status.outputs.status != 'verified'
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: ${{ inputs.STATUS }}

      - name: Show issue key found message
        if: steps.find.outcome == 'success'
        run: echo "### Found JIRA issue key '${{ steps.find.outputs.issue }}'" >> $GITHUB_STEP_SUMMARY

      - name: Show no issue moved because of verified state
        if: steps.find.outcome == 'success' && steps.check-status.outputs.status == 'verified'
        run: echo "### JIRA issue not moved because its state is 'Verified'" >> $GITHUB_STEP_SUMMARY

      - name: Show no issue key found message
        if: steps.find.outcome != 'success'
        run: echo "### No JIRA issue key found in '${{ inputs.BRANCH_OR_COMMIT_TITLE }}'" >> $GITHUB_STEP_SUMMARY
