name: Jira Create TODO Issues

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_NATIVE_GROUP:
        required: false
        type: string
        default: 'Native'
      PROJECT_KEY:
        required: true
        type: string
      ISSUE_TYPE:
        required: false
        type: string
        default: Task
      ISSUE_DESCRIPTION:
        required: false
        type: string
        default: "Created automatically via GitHub Actions"
      LINK:
        required: false
        type: string
        default: ""

jobs:
  create-todo-jira-issue:
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_NATIVE_GROUP }}

    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: ${{ inputs.PROJECT_KEY }}
        issuetype: ${{ inputs.ISSUE_TYPE }}
        description: ${{ inputs.ISSUE_DESCRIPTION }} ${{ inputs.LINK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
