name: Jira Create TODO Issues

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      PROJECT_KEY:
        required: true
        type: string
      ISSUE_TYPE:
        required: false
        type: string
        default: Task
      ISSUE_DESCRIPTION:
        required: false
        type: string
        default: "Created automatically via GitHub Actions"
      LINK:
        required: false
        type: string
        default: ""

jobs:
  create-todo-jira-issue:
    runs-on: ${{ fromJson(inputs.LABELS) }}

    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create TODO
      id: create
      uses: atlassian/gajira-todo@v3
      with:
        project: ${{ inputs.PROJECT_KEY }}
        issuetype: ${{ inputs.ISSUE_TYPE }}
        description: ${{ inputs.ISSUE_DESCRIPTION }} ${{ inputs.LINK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Show no todo found message
      if: steps.create.outcome == ''
      run: echo "### No new TODO found." >> $GITHUB_STEP_SUMMARY

    - name: Show todo found message
      if: steps.create.outcome != ''
      run: echo "### Found at least 1 issue." >> $GITHUB_STEP_SUMMARY
