name: Lint, check and build a Javascript app

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "zupit-agents"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      NODE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      RUN:
        required: false
        type: boolean
        default: true
      PROJECT:
        required: false
        type: string
        default: ""
      IMAGE:
        required: false
        type: string
        default: "ubuntu:23.04"

env: "${{ secrets }}"

jobs:
  lint-check-build:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/*/package-lock.json'

      - name: Install Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ env.github_token }}
        run: npm ci
        shell: bash

      # Workaround for git not working in two separate folders
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git
        run: |
          apt-get update && apt-get install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run affected lint and build
        run: npx nx affected -t lint build --base=origin/main --head=HEAD
