name: Node.js commond workflow

on:
  workflow_call:
    inputs:
      # Projects inputs
      DJANGO_IMAGE:
        required: true
        type: string
      DJANGO_PATH:
        required: true
        type: string
      DJANGO_MIGRATIONS_CHECK_APPS:
        required: false
        type: string
        default: ""
      BUILT_DJANGO_IMAGE: #da spostare negli altri workflow (testing, staging, ..)
        required: false
        type: string
        default: django
      DJANGO_DOCKER_PATH: #da spostare negli altri workflow (testing, staging, ..)
        required: true
        type: string
      # Workflow inputs
      DJANGO_CI_LABELS:
        required: true
        type: string




jobs:
  lint-check-build:
    uses:
      ./.github/workflows/node-step-format-lint-build.yml
    with:
      LABELS: ${{inputs.DJANGO_CI_LABELS}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      NODE_VERSION: ${{inputs.NODE_VERSION}}
    secrets: inherit

  cypress-run:
    uses:
      ./.github/workflows/node-step-test-cypress.ym
    with:
      LABELS: ${{inputs.DJANGO_CI_LABELS}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      CYPRESS_IMAGE: ${{inputs.CYPRESS_IMAGE}}
    secrets: inherit

