name: Test Javascript apps using Cypress

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      CYPRESS_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: true
        type: string
      BROWSER:
        required: false
        type: string
        default: "chrome"
      TIMEOUT:
        required: false
        type: number
        default: 30
      RUN:
        required: false
        type: boolean
        default: true

env: "${{secrets}}"

jobs:
  cypress-run:
    timeout-minutes: ${{ inputs.TIMEOUT }}
    runs-on: ${{ fromJson(inputs.LABELS) }}
    container:
      image: ${{ inputs.CYPRESS_IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ inputs.RUN }}
      - run: npm ci
        if: ${{ inputs.RUN }}
      - name: Cypress run
        uses: cypress-io/github-action@v4
        if: ${{ inputs.RUN }}
        with:
          install: false
          command: npm run ci:e2e
          working-directory: ${{ inputs.WORKING_DIRECTORY }}
          browser: ${{ inputs.BROWSER }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: ${{ inputs.RUN }}
        with:
          name: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
          path: ${{ inputs.WORKING_DIRECTORY }}/coverage/lcov.info
          retention-days: 1
      - run: echo "Done!"