name: Node build and deploy to Azure Storage

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      RELEASE_ENVIRONMENT:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      OUTPUT_DIRECTORY:
        required: true
        type: string
      STORAGE_ACCOUNT_NAME:
        required: true
        type: string
      PURGE_CDN:
        required: false
        type: boolean
        default: true
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      CDN_PROFILE_NAME:
        required: false
        type: string
        default: ""
      CDN_ENDPOINT_NAME:
        required: false
        type: string
        default: ""
      CDN_RG_NAME:
        required: false
        type: string
        default: ""

env: "${{secrets}}"

jobs:
  angular-build-and-deploy-azure-storage:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    environment: ${{ inputs.RELEASE_ENVIRONMENT }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Deploy to Azure Storage
        uses: zupit-it/pipeline-templates/.github/actions/node/build@MIGI-41/angular-pipeline-to-azure-storage
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          RELEASE_ENVIRONMENT: ${{ inputs.RELEASE_ENVIRONMENT }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_ARGS: ${{ inputs.BUILD_ARGS }}

      - name: Deploy to Azure Storage
        uses: zupit-it/pipeline-templates/.github/actions/azure/storage/deploy@MIGI-41/angular-pipeline-to-azure-storage
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BINARIES_DIRECTORY: ${{ inputs.OUTPUT_DIRECTORY }}
          AZURE_CREDENTIALS: ${{ secrets.CI_AZURE_CREDENTIALS }}
          STORAGE_ACCOUNT_NAME: ${{ inputs.STORAGE_ACCOUNT_NAME }}
          CDN_PROFILE_NAME: ${{ inputs.CDN_PROFILE_NAME }}
          CDN_ENDPOINT_NAME: ${{ inputs.CDN_ENDPOINT_NAME }}
          CDN_RG_NAME: ${{ inputs.CDN_RG_NAME }}
          PURGE_CDN: ${{ inputs.PURGE_CDN }}
