name: Lint, check and build a Javascript app

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      RUN:
        required: false
        type: boolean
        default: true

env: "${{secrets}}"

jobs:
  lint-check-build:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v3
      if: ${{ inputs.RUN }}
    - name: Use Node.js ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      if: ${{ inputs.RUN }}
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.WORKING_DIRECTORY }}/package-lock.json

    - run: npm ci
      if: ${{ inputs.RUN }}
    - run: npm run ci:format:check
      if: ${{ inputs.RUN }}
    - run: npm run ci:lint
      if: ${{ inputs.RUN }}
    - run: npm run ci:build
    - run: echo "Done!"
