name: Node build and deploy to Azure Storage

on:
  workflow_call:
    inputs:
      NATIVE_CI_LABELS:
        required: true
        type: string
      CONTAINER_CI_LABELS:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      RELEASE_ENVIRONMENT:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      OUTPUT_DIRECTORY:
        required: true
        type: string
      STORAGE_ACCOUNT_NAME:
        required: true
        type: string
      PURGE_CDN:
        required: false
        type: boolean
        default: true
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      CDN_PROFILE_NAME:
        required: false
        type: string
        default: ""
      CDN_ENDPOINT_NAME:
        required: false
        type: string
        default: ""
      CDN_RG_NAME:
        required: false
        type: string
        default: ""
      ENV_VARIABLES:
        required: false
        type: string
        default: '{}'
      PROJECT:
        required: false
        type: string
        default: ""
      IMAGE:
        required: false
        type: string
        default: "ubuntu:23.04"
      DIST_PATH:
        required: true
        type: string


env: "${{secrets}}"

jobs:
  build-node-project:
    runs-on: ${{ fromJson(inputs.CONTAINER_CI_LABELS) }}
    container:
      image: ${{ inputs.IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    steps:
      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/node/build@v1.2.0
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          RELEASE_ENVIRONMENT: ${{ inputs.RELEASE_ENVIRONMENT }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_ARGS: ${{ inputs.BUILD_ARGS }}
          PROJECT: ${{ inputs.PROJECT }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-build
          path: ${{ inputs.WORKING_DIRECTORY }}/${{ inputs.DIST_PATH }}
          retention-days: 1

  node-deploy-azure-storage:
    runs-on: ${{ fromJson(inputs.NATIVE_CI_LABELS) }}
    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    environment: ${{ inputs.RELEASE_ENVIRONMENT }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    needs: [ build-node-project ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-build
          path: ${{ inputs.WORKING_DIRECTORY }}/${{ inputs.DIST_PATH }}

      - name: Deploy to Azure Storage
        uses: zupit-it/pipeline-templates/.github/actions/azure/storage/deploy@v1.2.0
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BINARIES_DIRECTORY: ${{ inputs.OUTPUT_DIRECTORY }}
          AZURE_CREDENTIALS: ${{ secrets.CI_AZURE_CREDENTIALS }}
          STORAGE_ACCOUNT_NAME: ${{ inputs.STORAGE_ACCOUNT_NAME }}
          CDN_PROFILE_NAME: ${{ inputs.CDN_PROFILE_NAME }}
          CDN_ENDPOINT_NAME: ${{ inputs.CDN_ENDPOINT_NAME }}
          CDN_RG_NAME: ${{ inputs.CDN_RG_NAME }}
          PURGE_CDN: ${{ inputs.PURGE_CDN }}
