name: Angular Linter, Check and Build Workflow

on:
  workflow_call:
    inputs:
      LABELS:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ fromJson(inputs.LABELS) }}
    defaults:
      run:
        working-directory: ${{ fromJson(inputs.WORKING_DIRECTORY) }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ fromJson(inputs.NODE_VERSION) }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ fromJson(inputs.NODE_VERSION) }}
        cache: 'npm'

    - run: npm ci
    - run: npm run ci:format:check
    - run: npm run ci:lint
    - run: npm run ci:build
