name: Lint, check and build a Javascript app

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "zupit-agents"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      NODE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      RUN:
        required: false
        type: boolean
        default: true
      PROJECT:
        required: false
        type: string
        default: ""
      IMAGE:
        required: false
        type: string
        default: "ubuntu:23.04"

env: "${{ secrets }}"

jobs:
  lint-check-build:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: Ensure necessary packages are installed
        run: |
          apt-get update
          apt-get install -y unzip git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash

        # Workaround for git not working in two separate folders
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: v1.1.29

      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ env.github_token }}
        run: bun install --frozen-lockfile

        shell: bash
      - name: Run affected lint and build
        run: bun nx affected -t build --base=origin/main --head=HEAD --verbose
