name: Node.js commond workflow

on:
  workflow_call:
    inputs:
      # Projects inputs
      WORKING_DIRECTORY:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      CYPRESS_IMAGE:
        required: true
        type: string
      # Workflow inputs
      NATIVE_CI_LABELS:
        required: true
        type: string
      CONTAINER_CI_LABELS:
        required: true
        type: string

jobs:
  lint-check-build:
    uses:
      ./.github/workflows/node-step-format-lint-build.yml
    with:
      LABELS: ${{ inputs.NATIVE_CI_LABELS }}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      NODE_VERSION: ${{inputs.NODE_VERSION}}
    secrets: inherit

  cypress-run:
    uses:
      ./.github/workflows/node-step-test-cypress.ym
    with:
      LABELS: ${{ inputs.CONTAINER_CI_LABELS }}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      CYPRESS_IMAGE: ${{inputs.CYPRESS_IMAGE}}
    secrets: inherit

