name: Python package

on:
  workflow_call:
    inputs:
      django_image:
        required: true
        type: string

jobs:
  build:

    runs-on: test-pipeline
    container: python:3.9.4-slim-buster

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd backend
          if [ -f lint-requirements.txt ]; then pip install -r lint-requirements.txt; fi
      - name: Lint with flake8
        run: |
         python -m flake8 .
      - name: Lint with black
        run: |
         python -m black --check .
