name: Sonar analyze with artifacts

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: 'Container'
      WORKING_DIRECTORY:
        required: true
        type: string
      SONAR_IMAGE:
        required: false
        type: string
        default: "sonarsource/sonar-scanner-cli"
      SONAR_HOST_URL:
        required: false
        type: string
        default: "https://sonarqube.zupit.software"
      CHECK_QUALITY_GATE:
        required: false
        type: boolean
        default: false

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonar-analyze:
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: ${{ inputs.SONAR_IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ inputs.WORKING_DIRECTORY }}
          args: >
            -Dsonar.qualitygate.wait=${{ inputs.CHECK_QUALITY_GATE }}
            -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }}
