name: Sonar analyze with artifacts

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "zupit-agents"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      WORKING_DIRECTORY:
        required: true
        type: string
      SONAR_IMAGE:
        required: false
        type: string
        default: "sonarsource/sonar-scanner-cli"
      CHECK_QUALITY_GATE:
        required: false
        type: boolean
        default: false
      DOWNLOAD_ARTIFACT:
        required: false
        type: boolean
        default: true
      ARTIFACT_FILENAME:
        required: false
        type: string
        default: ""
      ARTIFACT_PATH:
        required: false
        type: string
        default: ".coverage-reports/"

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  sonar-analyze:
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: ${{ inputs.SONAR_IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sonar step analyze with artifacts
        id: sonar
        uses: zupit-it/pipeline-templates/.github/actions/sonar/analyze@v1.22.4
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          CHECK_QUALITY_GATE: ${{ inputs.CHECK_QUALITY_GATE }}
          DOWNLOAD_ARTIFACT: ${{ inputs.DOWNLOAD_ARTIFACT }}
          ARTIFACT_FILENAME: ${{ inputs.ARTIFACT_FILENAME }}
          ARTIFACT_PATH: ${{ inputs.ARTIFACT_PATH }}
        env: "${{secrets}}"
