name: Springboot common

on:
  workflow_call:
    inputs:
      NATIVE_CI_LABELS:
        required: true
        type: string
      CONTAINER_CI_LABELS:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      JAVA_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: false
        type: string
        default: "target"
      MAVEN_USER_HOME:
        required: false
        type: string
        default: "./m2"
      EXTRA_MAVEN_ARGS:
        required: false
        type: string
        default: ""
      USE_CI_POSTGRES:
        required: false
        type: boolean
        default: true

env: "${{secrets}}"

jobs:
  springboot-lint-check:
    uses:
      ./.github/workflows/springboot-step-lint-check.yml
    with:
      LABELS: ${{inputs.CONTAINER_CI_LABELS}}
      JAVA_IMAGE: ${{inputs.JAVA_IMAGE}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      MAVEN_USER_HOME: ${{inputs.MAVEN_USER_HOME}}
      EXTRA_MAVEN_ARGS: ${{inputs.EXTRA_MAVEN_ARGS}}
    secrets: inherit

  springboot-tests:
    uses:
      ./.github/workflows/springboot-step-tests.yml
    with:
      LABELS: ${{inputs.CONTAINER_CI_LABELS}}
      JAVA_IMAGE: ${{inputs.JAVA_IMAGE}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      MAVEN_USER_HOME: ${{inputs.MAVEN_USER_HOME}}
      EXTRA_MAVEN_ARGS: ${{inputs.EXTRA_MAVEN_ARGS}}
      COVERAGE_ARTIFACT_NAME: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
      USE_CI_POSTGRES: ${{ inputs.USE_CI_POSTGRES }}
    secrets: inherit
