name: Run SpringBoot tests

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: 'Container'
      WORKING_DIRECTORY:
        required: true
        type: string
      JAVA_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: true
        type: string
      MAVEN_USER_HOME:
        required: false
        type: string
        default: "./m2"
      EXTRA_MAVEN_ARGS:
        required: false
        type: string
        default: ""
      USE_CI_POSTGRES:
        required: false
        type: boolean
        default: true
      SPRING_APPLICATION_JSON:
        required: false
        type: string
        default:
      RUN:
        required: false
        type: boolean
        default: true
      DATABASE:
        required: false
        type: string
        description: 'Database to use: postgres or mysql'
        default: 'postgres'

env: "${{secrets}}"

jobs:
  springboot-run-tests:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: ${{ inputs.JAVA_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    services:
      ${{ inputs.DATABASE }}:
        image: ${{ inputs.DATABASE == 'postgres' && 'postgres' || 'mysql/mysql-server' }}
        env:
          ${{ inputs.DATABASE == 'postgres' && 'POSTGRES_USER' || 'MYSQL_ROOT_USER' }}: java-runner
          ${{ inputs.DATABASE == 'postgres' && 'POSTGRES_PASSWORD' || 'MYSQL_ROOT_PASSWORD' }}: java-runner
          ${{ inputs.DATABASE == 'postgres' && 'POSTGRES_DB' || 'MYSQL_DATABASE' }}: java
          ${{ inputs.DATABASE == 'mysql' && 'MYSQL_USER' }}: java-runner
          ${{ inputs.DATABASE == 'mysql' && 'MYSQL_PASSWORD' }}: java-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          ./mvnw -ntp verify -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
          ./mvnw -ntp jacoco:report -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
        env:
          SPRING_APPLICATION_JSON: ${{ inputs.USE_CI_POSTGRES && inputs.SPRING_APPLICATION_JSON || '{}' }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
          path: |
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.xml
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.class
          retention-days: 1
